version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hurumap
      MYSQL_USER: hurumap
      MYSQL_PASSWORD: hurumap
      MYSQL_ROOT_PASSWORD: hurumap

  pma:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: hurumap

  es:
    build: ./docker/elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"

  web:
    image: wordpress
    depends_on:
      - db
      - es
    restart: always
    ports:
      - 80:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./.htaccess:/var/www/html/.htaccess
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: hurumap
      WORDPRESS_DB_USER: hurumap
      WORDPRESS_DB_PASSWORD: hurumap
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
       
        /* JWT Authentication */
        define('JWT_AUTH_CORS_ENABLE', true);
        define('JWT_AUTH_SECRET_KEY', 'secret');

        /* Default User */
        define('WP_DEFAULT_USERNAME','username');
        define('WP_DEFAULT_PASSWORD','password');     
      ELASTICSEARCH_INDEX: hurumap
      ELASTICSEARCH_HOST: http://es:9200
volumes:
  db-data:
